---
snmp:
  communities: 
    - key: community_RO_key
      acl: community_RO_acl
      write_permission: RO
    - key: community_RW_key
      acl: community_RW_acl
      write_permission: RW
  hosts:
    - server_ip: 1.1.1.1
      version: 1
    - server_ip: 2.2.2.2
      version: 1
ntp_servers:
  - 1.1.1.1
  - 3.3.3.3
  - 4.4.4.4
