---
# tasks file for acl
- name: Deploy ACL tasks for Cisco IOS
  when: ansible_network_os == "cisco.ios.ios"
  notify: Save IOS Config
  block: 
    - name: Deploy ACL Config for Cisco IOS
      cisco.ios.ios_acls:
        config: "{{ acl_config }}"
        state: "{{ acl_state }}"
  
    
